apiVersion: v1
stringData:
  values.yaml: ENC[AES256_GCM,data:HizjuIcuZT3UF7DnPBbrCikKGNTBSYfe0TNXJqiQhRGotKVQawhUxG8KRJ1oMdBUveXjb0IHcZyDOlP1ZoNaxLFFdeX7CN6aW6NqKg4Ns/PIdmIQaPUxrGm8+WvE8CQNqYEarMjc8MD7oES3C/yLz8jpoQhl24OG8iWArscHkeQMzdnuazwvKU8jso98jEVafVVN5yI=,iv:hKcyfdiw71N7UAQCgWB4z1d6Jk1//U5aZeMGtIK/xnA=,tag:j2WBtZIzD9FbRwIUDycEeg==,type:str]
kind: Secret
metadata:
  name: tailscale-config
sops:
  age:
    - recipient: age16xc3m2q69s2le4hah3pcne50qn6mljhgc9mxekskwf0mp8fc0vaq5q5dz2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWaU9VSGxTMDRHbGo2SGFF
        d1gvanRoOTF4dnpCZmo1U1IzYkpFWW1BYlYwCmlzWVBtbytmbHZMUXU4YmFRNEZB
        eEJ1WDd5aFBDd053WkZ1U3R6WDlQSVkKLS0tIDdvdFhrNXBLTHB5VGFISFBUdmky
        TnBWQXFBcXU3N0ZjTEFQVEJtY1dUMFkKgi0QgcV+kLO862h0rOLCX3BW21PY+Z35
        /4B4eiQ339MTcObp26sko9/mCcz9oEeIHfg5RpWSz6lUP+38tjQlDg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-12T18:15:11Z"
  mac: ENC[AES256_GCM,data:PGn9SdRfh16JB0GfrSQIn9Q5DOLSXHNUn4KHt9k8GlScDTcwjVTXplYi+7JB0QJEFsp/TmH9lkNeTMUpMknAKCEtoGvXTNHiQIfzrt/VEoRJvk1zLLxuGVtOahZGGMZ2t9GFa4HAdmDWQZOZ7ALy0d6GeBteWZ+fvu0+AbjHhIU=,iv:rk46D486EmW6K0o2viHBtQqn8GtwC22V0UI9FJxhr08=,tag:MPHfC36TTziEgKUE6umzhQ==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.12.2
