apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rathole
spec:
  interval: 24h
  chart:
    spec:
      chart: ./appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1h
  values:
    apps:
      - name: rathole
        image: rapiz1/rathole:v0.5.0@sha256:52f3a087ccb89358705de1f6ac0e923a00d066fe9a8548ab7a79ad21adab93fa
        containerSpec:
          args:
            - --client
            - /client.toml
        volumeMounts:
          - name: rathole-config
            mountPath: /client.toml
            subPath: client.toml
        volumes:
          - name: rathole-config
            secret:
              secretName: rathole-config
