apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: waf
spec:
  interval: 24h
  chart:
    spec:
      chart: ./appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1h
  values:
    apps:
      - name: dummy
        image: traefik/whoami@sha256:200689790a0a0ea48ca45992e0450bc26ccab5307375b41c84dfc4f2475937ab
        service: 80
      - name: waf
        image: owasp/modsecurity-crs:4.29.0-nginx-alpine-202609230209@sha256:a9e7ac05d878b563d197f8b3eccd4407ffdf914f2f0cdf7cec9a528bfb1c28f7
        service: 8080
        env:
        - name: ALLOWED_METHODS
          value: GET HEAD POST OPTIONS DELETE PUT PATCH
        - name: BLOCKING_PARANOIA
          value: "1"
        - name: ANOMALY_INBOUND
          value: "5"
        - name: ANOMALY_OUTBOUND
          value: "5"
        - name: BACKEND
          value: "http://dummy"
