apiVersion: v1
stringData:
  address: ENC[AES256_GCM,data:WlJ1dkEwm1klFLPYLweHIgxjKA0lLFaG/3A4j/ZnKl6Ph3dEEEllAeYz/Z5Mz/f9MIEk7QN0JStpdvfhCcekev7ZJlF/BTCkGfG9N/Tf,iv:Zu0U5y5tBQ2x4iFoSYvOGGV/Fxp/+O0xOgmReyDc39k=,tag:hLWRktenOdmcwfPa9uMYKg==,type:str]
kind: Secret
metadata:
  name: discord-webhook
  namespace: flux-system
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBeWtJTmhFU0VDTXhOanpz
        RFEwNG54aHg2ckNyc3FQb2JKNm9WN01raVFrCld0S21QTlpxSGxXWE55Ymt0eFI2
        L0NIMDgwWisrajFyTkJGeEMyME5PRlUKLS0tIHQySW5FK2tMSDVDdHhYL2sxUTNL
        dXQ3RVc0b1d6TDBmMFg2WURZRVFweHcKtFqvMGDJtrK8uThhTqK/XvtkWkrjrqu1
        qcHTtBFNF0+LIDUuvhOXFDfKNfl3Bp/pOHSVF7A07wdQTWXIe0S8HQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16xc3m2q69s2le4hah3pcne50qn6mljhgc9mxekskwf0mp8fc0vaq5q5dz2
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  lastmodified: "2026-06-11T16:02:01Z"
  mac: ENC[AES256_GCM,data:8APu6rR7MMwu7XjzwRoDZang12Zch79PZJeGkxAG9qBKvUHK4ww3H05J8+QTObn39DdVVayGJywE5S5afyLIrWVPQJa8HuKedunp45KFskF1gPoF8LYtHC8S/bYtxD9CoEydrSsPiMM6Ps5Kqlq169fwWkEYDHd9opDvw3e/Os8=,iv:wOC+5T5KKl471l4IfUExVVY5nCjrEJ60ENMye3Wj4KM=,tag:Try54/Swnu/KDRi8j2OuMw==,type:str]
  version: 3.13.1
