apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: critical
value: 1000
globalDefault: false
description: "Use to be last to be killed, first to be scheduled"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low
value: 10
globalDefault: true
description: "Default, non critical services that might get evicted first"
