apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  interval: 10m
  chart:
    spec:
      chart: ./appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: jellyfin
        image: ghcr.io/jellyfin/jellyfin:12.1@sha256:008ec8024bdaaa6f0a3f0de468e185633eeba9d67c56936e8dbf5ef6b8d6200f
        podSpec:
          securityContext:
            supplementalGroups: # for DRI access
              - 993
        containerSpec:
          securityContext:
            privileged: true

        volumeMounts:
          - name: jellyfin-cache
            mountPath: /cache
          - name: jellyfin-config
            mountPath: /config
          - name: jellyfin-shows
            mountPath: /data/shows
          - name: jellyfin-music
            mountPath: /data/music
          - name: jellyfin-books
            mountPath: /data/books
          - name: 'render-device'
            mountPath: '/dev/dri/renderD128'

        volumes:
          - name: jellyfin-cache
            persistentVolumeClaim:
              claimName: jellyfin-cache
          - name: jellyfin-config
            persistentVolumeClaim:
              claimName: jellyfin-config
          - name: jellyfin-music
            persistentVolumeClaim:
              claimName: jellyfin-music
          - name: jellyfin-shows
            persistentVolumeClaim:
              claimName: jellyfin-shows
          - name: jellyfin-books
            persistentVolumeClaim:
              claimName: jellyfin-books
          - name: 'render-device'
            hostPath:
              path: '/dev/dri/renderD128'

        service: 8096
        pvc:
          - jellyfin-music
          - jellyfin-shows
          - jellyfin-config
          - jellyfin-cache
          - jellyfin-books
        ingress:
          domain: jellyfin.cocointhe.cloud
          public: true
