apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  interval: 10m
  chart:
    spec:
      chart: appchart
      version: "1.8.0"
      sourceRef:
        kind: HelmRepository
        name: appchart
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: jellyfin
        image: ghcr.io/jellyfin/jellyfin:10.11.11@sha256:45f648c382a0c8b552582fcea40e95cb17c5d475473a891cba0eb7523fb92112
        volumeMounts:
          - name: jellyfin-cache
            mountPath: /cache
          - name: jellyfin-config
            mountPath: /config
          - name: jellyfin-shows
            mountPath: /data/shows
          - name: jellyfin-music
            mountPath: /data/music

        volumes:
          - name: jellyfin-cache
            persistentVolumeClaim:
              claimName: jellyfin-cache
          - name: jellyfin-config
            persistentVolumeClaim:
              claimName: jellyfin-config
          - name: jellyfin-music
            persistentVolumeClaim:
              claimName: jellyfin-music
          - name: jellyfin-shows
            persistentVolumeClaim:
              claimName: jellyfin-shows

        service: 8096
        pvc:
          - jellyfin-music
          - jellyfin-shows
          - jellyfin-config
          - jellyfin-cache

        ingress:
          domain: jellyfin.cocointhe.cloud
          public: true

