apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metube
spec:
  interval: 10m
  chart:
    spec:
      chart: ./appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: metube
        image: ghcr.io/alexta69/metube:2026.07.21@sha256:b0a27dc1505460d2eaf9a6713b486a01d11733043622e49a2572ee5cbe9f0503
        env:
          - name: DOWNLOAD_DIR
            value: /downloads/shows
          - name: AUDIO_DOWNLOAD_DIR
            value: "/downloads/music"

        service: 8081
        ingress:
          domain: tube.cocointhe.cloud
        volumeMounts:
          - name: jellyfin-shows
            mountPath: /downloads/shows
          - name: jellyfin-music
            mountPath: /downloads/music
        volumes:
          - name: jellyfin-shows
            persistentVolumeClaim:
              claimName: jellyfin-shows
          - name: jellyfin-music
            persistentVolumeClaim:
              claimName: jellyfin-music
