apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metube
spec:
  interval: 10m
  chart:
    spec:
      chart: appchart
      version: "1.8.0"
      sourceRef:
        kind: HelmRepository
        name: appchart
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: metube
        image: ghcr.io/alexta69/metube:2026.06.06@sha256:acf201148260de39b7eeb316f3cd611088e4a707ff4a3f1ebf460fa72054c6e5
        env:
        - name: DOWNLOAD_DIR
          value: /downloads/shows
        - name: AUDIO_DOWNLOAD_DIR
          value: "/downloads/music" 

        service: 8081
        ingress:
          domain: tube.cocointhe.cloud
        volumeMounts:
          - name: jellyfin-shows
            mountPath: /downloads/shows
          - name: jellyfin-music
            mountPath: /downloads/music
        volumes:
          - name: jellyfin-shows
            persistentVolumeClaim:
              claimName: jellyfin-shows
          - name: jellyfin-music
            persistentVolumeClaim:
              claimName: jellyfin-music