apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: musicgrabber
spec:
  interval: 10m
  chart:
    spec:
      chart: appchart
      version: "1.8.0"
      sourceRef:
        kind: HelmRepository
        name: appchart
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: musicgrabber
        image: g33kphr33k/musicgrabber:2.6.6@sha256:dad8dec4e32671ef7326d31f58ea626fa4622571e65c6bb34459bc2648f1fead
        env:
        - name: MUSIC_DIR
          value: "/downloads/music" 
        - name: LISTEN_ADDR
          value: 0.0.0.0
        - name: ENABLE_MUSICBRAINZ
          value: "true"
        - name: DEFAULT_CONVERT_TO_FLAC
          value: "true"
        - name: DB_PATH
          value: /data/music_grabber.db
        - name: JELLYFIN_URL
          value: http://jellyfin:8096
        - name: JELLYFIN_API_KEY
          value: 62f595a2d8504077b04a8171d5c17cc4

        pvc:
        - musicgrabber-config
        service: 8080
        ingress:
          domain: grab.cocointhe.cloud
        volumeMounts:
          - name: jellyfin-music
            mountPath: /downloads/music
          - name: musicgrabber-config
            mountPath: /data

        volumes:
          - name: jellyfin-music
            persistentVolumeClaim:
              claimName: jellyfin-music
          - name: musicgrabber-config
            persistentVolumeClaim:
              claimName: musicgrabber-config