apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 10m
  chart:
    spec:
      chart: ./appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: qbittorrent
        image: linuxserver/qbittorrent:5.2.2@sha256:bca2cf536c00900f0b8fb62ca3dcbed8ee64293165d41c8240d2cc952d4ef048
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
        volumeMounts:
          - name: jellyfin-shows
            mountPath: /downloads
          - name: qbittorrent-config
            mountPath: /config
        volumes:
          - name: jellyfin-shows
            persistentVolumeClaim:
              claimName: jellyfin-shows
          - name: qbittorrent-config
            persistentVolumeClaim:
              claimName: qbittorrent-config
        service: 8080
        ingress:
          domain: torrents.cocointhe.cloud
        pvc:
          - qbittorrent-config
