apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: falco
spec:
  interval: 24h
  url: https://falcosecurity.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: falco
      version: 9.1.0
      sourceRef:
        kind: HelmRepository
        name: falco
      interval: 1h
  releaseName: falco
  valuesFrom:
  - kind: Secret
    name: falcosidekick-config
  values:
    collectors:
      containerEngine:
        engines:
          docker:
            enabled: false
          podman:
            enabled: false
          lxc:
            enabled: false
          libvirt_lxc:
            enabled: false
          bpm:
            enabled: false
      kubernetes:
        enabled: true
    falcosidekick:
      enabled: true
      replicaCount: 1
    customRules:
      disable-false-positives.yaml: |
        - rule: Packet socket created in container
          enabled: false
      # normal communication to the api server
      allow-kube-vip-apiserver.yaml: |
        - rule: Contact K8S API Server From Container
          override:
            condition: append
          condition: >
            and not k8s.ns.name in (
              kube-vip,
              kyverno,
              vpa,
              nfs-system,
              flux-system,
              system-upgrade,
              cert-manager,
              longhorn-system
            ) and not (
              container.name = "prometheus-server" and
              k8s.ns.name = "watchtower"
            ) and not (
              container.name = "traefik-tunnel" and
              k8s.ns.name = "ingress"
            ) and not (
              container.name = "traefik" and
              k8s.ns.name = "ingress"
            ) and not (
              proc.name = "kube-vip"
            )
      # explo launches a cron for scheduling
      allow-explo-crond.yaml: |
        - rule: Drop and execute new binary in container
          override:
            condition: append
          condition: >
            and not (
              k8s.ns.name = "media" and
              container.image.repository = "ghcr.io/lumepart/explo" and
              proc.pname = "crond"
            )
      # at startup, it seems owasp is doing some templating for the rules
      allow-owasp-shell.yaml: |
        - rule: Run shell untrusted
          override:
            condition: append
          condition: >
            and not (
              k8s.ns.name = "ingress" and
              container.image.repository = "docker.io/owasp/modsecurity-crs" and
              container.name = "waf" and
              proc.pname = "nginx"
            )
      # sshing into the host trigger some sensitive read files
      allow-ssh-host.yaml: |
        - rule: Read sensitive file untrusted
          override:
            condition: append
          condition: >
            and not (
              container.id = "host"
            )

      # explo is doing some stuff
      allow-explo-cron.yaml: |
        - rule: Drop and execute new binary in container
          override:
            condition: append
          condition: >
            and not (
              container.name = "explo" and
              k8s.ns.name = "media"
            )
