apiVersion: v1
kind: Secret
metadata:
  name: falcosidekick-config
stringData:
  values.yaml: ENC[AES256_GCM,data:NnbDdJ73/imEYRuOB+jDHnJNSmy6s4H0S9Gug1+5nzWSf3hqy8NB+yuhfowjnI84qHkS1FDio22PywPbaA/1gEtUFN0URdj/vQE9XO8Y4VjG/Iafg5rt2d0fG+mC5zWO8uU40hVsclQg4hV2+HuJdnonaHSBs1ATJMje0O72zv0n1DKTT/if5jNnbOvvkgf0D9Ni0eDoHtGQsdcEj29B8ZGTeDy7VFnBM9gXcjoTHUnV1zVyIGVA6xt13mntu63iVwQX15Wp8sl8XyQBgCKacwDF5i4NStltZXzp6XcsY9JQDKofH/YP0ZpjR5WZUUxEDWhXZl1ra672ruVFcDcORLrMFI656fYLcaj1u8UddO43OwJWka51eypFr9T4OPCfSh2h2hvI,iv:WgzMa1ejllci2LSzqgGslInk08PGYS+FBjLUDXBepN8=,tag:fkKhHT1uSwe8nlFXeTHTTA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TVJVWk5nRVVIMUJoN2k4
        OWFLSm0zZzJzaVZWejY5V0dxcFEzeW5VWmdnCkRJSGtJQzJROW5KNmNaaDlWdWE4
        RXZMS1NSUllZY2RWekVGNVNDbDlCcTAKLS0tIDN4N2syNFFWTEEwV0VwaDB5Y0xC
        amFxcW12RzBXZ3dwenBoaXUvYUNwWW8KZzmEYiNkkU2E/mvEN42D7VSHZ1Yn2Ps5
        28XmDAyt6i0Sat2/6FAeQupOU4lNOYUOVKMeY18Q7vuctbN83x/Iwg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16xc3m2q69s2le4hah3pcne50qn6mljhgc9mxekskwf0mp8fc0vaq5q5dz2
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$|secrets$)
  lastmodified: "2026-10-01T21:24:29Z"
  mac: ENC[AES256_GCM,data:HZWrjqCaA8pBJqU3nI9Dpiwy254oiYFpbo6bXnEqV3zmFxzB+qMz3cU1gAimOHOv3HEn+CurJr2ocbgIl6+mw0KFB46FbQI4TDP86lvtb9v1YALu/qFIeAf3YRTdpfO+yzRPeFBc6pXHsF/Ba7pmp1YuNYnxa44xnHJSQjdEUnI=,iv:XSuhBa3eCuGvZlbHa3e8B0pQdNHugWGhWfzth15Lyok=,tag:tbQ3nUOmUo/o/C+4Tom8lw==,type:str]
  version: 3.13.3
