apiVersion: v1
kind: Secret
metadata:
  name: falcosidekick-config
stringData:
  values.yaml: ENC[AES256_GCM,data:kJIbeGGtdENRG4rphGZXUbNi2zBgMmNEjkcytbZpBHWw98VwnRnVJfliSBjK8ff0sH3RmJQEjfdRTxGnUvo6QMEI5FeqHAqVGewxcO1d/RY7MGvSFfxJPAcTZKJNnv+wlG/1IYQDd6RWGxORGvmMyrQ7wZ3AVT7wQ+gYmgZyZEr3SS3Lt6VEYGR8Ktc9lB/uVWrjFKH3k/zUY/oBP0/iG/WT3xgne5pXNb8ExNM5a3G9gLvhmzTIjccozun1gmUqEbjaEnj41yFRB6rARAwCk+zY2DEeWNRvTHy3NeBVdwrBtk2hePIrOYr59CgzGzlA6q+BxPlErmgyD9DJK1tEZFijElYojGKy1rbz7bZwJX5HZrcYRw50xYv9ER4RRVzptg==,iv:LX65QXr8IJBGu/bA3BwU4V5uayc6qv7Otp2PXVxiRL8=,tag:Ap8UbWjRpYgX4eyEL8IA7A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TVJVWk5nRVVIMUJoN2k4
        OWFLSm0zZzJzaVZWejY5V0dxcFEzeW5VWmdnCkRJSGtJQzJROW5KNmNaaDlWdWE4
        RXZMS1NSUllZY2RWekVGNVNDbDlCcTAKLS0tIDN4N2syNFFWTEEwV0VwaDB5Y0xC
        amFxcW12RzBXZ3dwenBoaXUvYUNwWW8KZzmEYiNkkU2E/mvEN42D7VSHZ1Yn2Ps5
        28XmDAyt6i0Sat2/6FAeQupOU4lNOYUOVKMeY18Q7vuctbN83x/Iwg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16xc3m2q69s2le4hah3pcne50qn6mljhgc9mxekskwf0mp8fc0vaq5q5dz2
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$|secrets$)
  lastmodified: "2026-06-17T07:47:08Z"
  mac: ENC[AES256_GCM,data:Oaelm8IvN9EE/68A/d9qQG+OqKfWwu9Tpi98Vx3kcZ6eXqjwJzFoYjiMB7UXHpEnazUztTIsepGU9ForvPWHzEXedxS0z0uU+41mOBOIv7UAYClik1wrMkoFNvyEcIFbNlQ5zszmpy1y4VztZg3xBaHtxCwQNo89/Us+0Dp4HBw=,iv:fJcVjUuIkhWVCvcLRziabig7gj8JhOdssvXnnIFBSRk=,tag:2dWM0VuDhaCwOvYmjtzZmQ==,type:str]
  version: 3.13.1
