apiVersion: v1
kind: Secret
metadata:
  name: falcosidekick-config
stringData:
  values.yaml: ENC[AES256_GCM,data:6ZZmpgIJjILJCvj+aUfJ9Cj6BOXJYvP307K4Mfzowh+Ec1+Q+Do6j9uVKq5TXSQ9pr59xHbmmm7OSuBmkwG8Izl1+i72bOIYluAsBpAmMrE8sW8ECYoNaaOxcZy6Q47DVAoKCCGRuiJlVbvfxu4IQWJBmke5y9hH97mM4q+9C72LFJGF5Jn3KZ7Mq/qSGBpshNiWLmZ04LoGcHFEPd6KEPgTYdqN+xOCpCkJjsQqli+OX2/hHcMkeTBQzrjLAnaXTKICB41CKTdtAWwcceb5XzbSUJAq1r9eQkJS2YuMIZlEZOj/Q+J4iYzYEMW4sKqYsosif4FREfxkTW94SNzD5tKb/oAe7TwUSsUE9HTOji9h3Ex6UHKCBiLWQ7y0H8ZhLiV7+cGCgwZAZXqZ6QIby1577OXntHtcxJQ+/wRrcwuNwMOVDhgNc4TpSlv6dVYRCa1y7w==,iv:jtShbOiBPi0hr8Qit7GWdkIX5NqwJOlQzdvnbubDdzk=,tag:sBN1L2wEE/70vg/uHE3XWQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TVJVWk5nRVVIMUJoN2k4
        OWFLSm0zZzJzaVZWejY5V0dxcFEzeW5VWmdnCkRJSGtJQzJROW5KNmNaaDlWdWE4
        RXZMS1NSUllZY2RWekVGNVNDbDlCcTAKLS0tIDN4N2syNFFWTEEwV0VwaDB5Y0xC
        amFxcW12RzBXZ3dwenBoaXUvYUNwWW8KZzmEYiNkkU2E/mvEN42D7VSHZ1Yn2Ps5
        28XmDAyt6i0Sat2/6FAeQupOU4lNOYUOVKMeY18Q7vuctbN83x/Iwg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16xc3m2q69s2le4hah3pcne50qn6mljhgc9mxekskwf0mp8fc0vaq5q5dz2
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$|secrets$)
  lastmodified: "2026-10-01T21:13:56Z"
  mac: ENC[AES256_GCM,data:WSlzCGCPv8VMato8tu0FSkHSuIkEAn85tPk+J/rXNml8l/a2DRW0wC384svLl6HkYXTCwYZFkLSb6BLCOpXe082iSt/+AOc1cfEMQ9xU74tRzo4pPKLdHcZmX7AfnyjXZ8aYvfiSPv1vTNleA3eLntvlk+KowDnZQDN9eceAL3E=,iv:X5YhiNLjG7Cpna65pVyS7G2Val5gIsOJMXle1XEurLU=,tag:sDXILyXzaa6YyxbzwV5mQw==,type:str]
  version: 3.13.3
