apiVersion: batch/v1
kind: CronJob
metadata:
  name: restic-backup
spec:
  schedule: "30 3 * * *"
  timeZone: "Europe/Paris"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          hostname: cluster # set hostname so the backups use this for consistency instead of a pod generated name
          containers:
            - image: gitea.cocointhe.cloud/coco/restic:v0.4.2
              name: restic-backup
              envFrom:
                - secretRef:
                    name: restic-config
              volumeMounts:
                - name: key-volume
                  mountPath: /tmp/key
                - mountPath: /backups
                  name: backup-repo
                  readOnly: false
                - mountPath: /data
                  name: data-root
                  readOnly: true
          volumes:
            - name: key-volume
              secret:
                secretName: sshkey
            - name: data-root
              hostPath:
                path: /data
                type: Directory
            - name: backup-repo
              hostPath:
                path: /backups
                type: Directory
