apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grist
spec:
  interval: 10m
  chart:
    spec:
      chart: ./appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: grist
        image: gristlabs/grist:1.7.18@sha256:fb19baff9653aa16d7c064bbab1da9a33ec0fa04bc78f3f818a788a06791328e
        containerSpec:
          envFrom:
            - secretRef:
                name: grist-config
        volumeMounts:
          - name: grist-data
            mountPath: /persist
        volumes:
          - name: grist-data
            persistentVolumeClaim:
              claimName: grist-data
        service: 8484
        pvc:
          - grist-data
        ingress:
          domain: grist.cocointhe.cloud
          public: true
