apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grist
spec:
  interval: 10m
  chart:
    spec:
      chart: appchart
      version: 1.8.0
      sourceRef:
        kind: HelmRepository
        name: appchart
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: grist
        image: gristlabs/grist:1.7.14@sha256:b8a48b6ace784fadb4a3981ad74024b218c1c02ba0c200c49b2fe425be465e15
        containerSpec:
          envFrom:
            - secretRef:
                name: grist-config
        volumeMounts:
          - name: grist-data
            mountPath: /persist
        volumes:
          - name: grist-data
            persistentVolumeClaim:
              claimName: grist-data
        service: 8484
        pvc:
          - grist-data
        ingress:
          domain: grist.cocointhe.cloud
          public: true
