apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: haven
spec:
  interval: 10m
  chart:
    spec:
      chart: appchart
      version: "1.8.0"
      sourceRef:
        kind: HelmRepository
        name: appchart
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: haven
        image: ghcr.io/ancsemi/haven:3.16.0@sha256:a5f0fafb5941078e6ad61317b4969a0883c050f22ee436c2f39c5a325b296f27
        # containerSpec:
        #   envFrom:
        #     - secretRef:
        #         name: haven-config
        volumeMounts:
          - name: haven-data
            mountPath: /data
        volumes:
          - name: haven-data
            persistentVolumeClaim:
              claimName: haven-data
        service: 3000
        ingress:
          domain: haven.cocointhe.cloud
          public: true
        pvc:
          - haven-data
