apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: haven
spec:
  interval: 10m
  chart:
    spec:
      chart: appchart
      version: "1.8.0"
      sourceRef:
        kind: HelmRepository
        name: appchart
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: haven
        image: ghcr.io/ancsemi/haven:3.10.12@sha256:4f92e7f3cba403a4adeefd9aefd6acf4877ac8279896db696415e7afff478b7b
        # containerSpec:
        #   envFrom:
        #     - secretRef:
        #         name: haven-config
        volumeMounts:
          - name: haven-data
            mountPath: /data
        volumes:
          - name: haven-data
            persistentVolumeClaim:
              claimName: haven-data
        service: 3000
        ingress:
          domain: haven.cocointhe.cloud
          public: true
        pvc:
          - haven-data
