apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: landingpage
spec:
  interval: 24h
  chart:
    spec:
      chart: ./appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: landingpage
        image: gitea.cocointhe.cloud/coco/landingpage:v0.4.0@sha256:aa1f06f847ba182af48a000859ae80b6bdb2ced0ae3d379c56dd82626763209d
        service: 5000
        ingress:
          public: true
          domain: cocointhe.cloud
        env:
          - name: LLM_API_URL
            value: http://192.168.1.129:8080/v1/chat/completions
          - name: RSS_FEEDS
            value: https://www.phoronix.com/phoronix-rss.php,https://lobste.rs/top/rss,https://hnrss.org/frontpage
        volumeMounts:
          - name: landingpage-data
            mountPath: /app/static
        volumes:
          - name: landingpage-data
            persistentVolumeClaim:
              claimName: landingpage-data
        pvc:
          - landingpage-data

---
# acess llamacpp host and prometheus
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-landingpage
spec:
  podSelector:
    matchLabels:
      app: landingpage
  policyTypes:
    - Egress
  egress:
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
          except:
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16
      ports:
      - protocol: TCP
        port: 443
    - to:
        - ipBlock:
            cidr: 192.168.1.129/32
    - to:
      - namespaceSelector: {}
        podSelector:
          matchLabels:
            app.kubernetes.io/name: prometheus
