apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home
spec:
  interval: 24h
  chart:
    spec:
      chart: ./appchart/charts/appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1h
  values:
    apps:
      - name: traefik
        image: traefik/whoami
        service: 80
        ingress:
          public: true
          domain: cocointhe.cloud
