apiVersion: v1
kind: Secret
metadata:
  name: nota-config
stringData:
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:4JRygs7l+L24v83jeA9VIUizdZAxsw0KbkFI1UPivHmu3cUD,iv:WZG5USYV1mLQA+TRTU1trnwsKcU0HwBxm00xfQJ5KJM=,tag:OFQulGfkeqgVER5YHDTSHg==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:1Yg2OfKt0T3QYq19rXkV0yo53vhGERyP+aofuN6s+po=,iv:+tN7f2v3yDOIQ/qQ1am2KhN8OFlA9ujPCBQLY9JuR2w=,tag:FZJ2fmqzKOOdQtg3YJsD+w==,type:str]
  OIDC_DISCOVERY_URL: ENC[AES256_GCM,data:CH2quWguVZGASnF2M4Wa2VlhJrJJpGa0Pd5nfTV+0CspSM8vmRN4BEHLC7qYKqTXe02Qi/F/eQBBO2rXAxImsp0=,iv:5dekG1AmZ3mAS4BP/uUQ6EPWZs9/aCL5hxJ8j7pwjqQ=,tag:E981vX025UUWhslOKdn1Sw==,type:str]
  SESSION_SECRET: ENC[AES256_GCM,data:1pw1jCxBgs73OpF+bzYtkU/ZSnVKRwL4tOUFuJcQu9Lxg+sOCS5Z6V80UstmfFwprtNQT7h89IX1Bk1k1hukLA==,iv:DpuFi34d3pQW1Tz0ogXKXaNNW9jxyzMfc6OLM9k7AT0=,tag:qQFr7/ozhd4l/gcA0EQLyA==,type:str]
sops:
  age:
    - recipient: age16xc3m2q69s2le4hah3pcne50qn6mljhgc9mxekskwf0mp8fc0vaq5q5dz2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZW9qZkJnWmlFdEs4T1J3
        REg3dHpyZWRCY3JSSzF2UVZvV1dXOFpWelI4Ck5FeDVGc3daNjdHeWkxWmV3am14
        NWtyQTI3MUtPSnNvUkQ2TlpuK01RZmsKLS0tIFI1Q0xLUHZZZHZCVnNPMFR3OFgv
        a3dsWnJHL1prcWI3a2NlMFpFUjNEaTgK6FNxXeJ451f/TuEbSnvK33PaZHA1NxFF
        uYVOJDwNhoVEsmbphXrnobAWBza/id8V00jWFBkuMjrNl8CTFNJP0w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T18:52:31Z"
  mac: ENC[AES256_GCM,data:mFiTrYWex5ZL/OWiwIg7p9Pjol+zYA8rfsliRkxfI6CwMEx3n0fFCe0imVVFIho44TEifRTN5EtfK6xZ2D+N81Fm5mXcTMVKgyv1Z8Xz0sZRfdhlzGxVv2lpyk5/7q1Da9m5tmBpqutVGjNMPtKHMRMqJuloZZNxiwu9lAHGRQ4=,iv:nKqxHxxlK7YDv1ap6hPGW/8Q7wLmg87m2hQ0FLPSlG4=,tag:YeZ7/za0Vw9W14jjBT6coQ==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$|secrets$)
  version: 3.12.1
