apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nota
spec:
  interval: 24h
  chart:
    spec:
      chart: ./appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: nota
        image: gitea.cocointhe.cloud/coco/nota:0.3.0@sha256:da78f71ff2037695e30cd8fe9282f9815e8a6d68c3b573649c44ea29c18f9697
        service: 8000
        anubis: true
        ingress:
          public: true
          domain: notes.cocointhe.cloud
        env:
          - name: BLOG_TITLE
            value: "> coco@nota:/"
        containerSpec:
          envFrom:
            - secretRef:
                name: nota-config
        volumeMounts:
          - name: nota-data
            mountPath: /app/data
        volumes:
          - name: nota-data
            persistentVolumeClaim:
              claimName: nota-data
        pvc:
          - nota-data
