apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rackpost
spec:
  interval: 10m
  chart:
    spec:
      chart: ./appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: rackpost
        image: gitea.cocointhe.cloud/coco/rackpost:v0.2.4
        volumeMounts:
          - name: rackpost-data
            mountPath: /data
        containerSpec:
          envFrom:
            - secretRef:
                name: rackpost-config
        volumes:
          - name: rackpost-data
            persistentVolumeClaim:
              claimName: rackpost-data
        service: 8000
        ingress:
          domain: rackpost.cocointhe.cloud
          public: true
        pvc:
          - rackpost-data
---
# rackpost -> webpushservices like mozilla, apple & google
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-rackpost-push-services
spec:
  podSelector:
    matchLabels:
      app: rackpost
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 443
