apiVersion: policies.kyverno.io/v1
kind: NamespacedMutatingPolicy
metadata:
  name: enforce-gvisor-runtime-class
  namespace: cloud
spec:
  matchConstraints:
    resourceRules:
      - apiGroups: ['']
        apiVersions: ['v1']
        operations: ['CREATE', 'UPDATE']
        resources: ['pods']
  mutations:
    - patchType: ApplyConfiguration
      applyConfiguration:
        expression: |
          Object{
            spec: Object.spec{
              runtimeClassName: "gvisor"
            }
          }
