{{- range .Values.apps }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  replicas: 1
  {{- if .deploymentSpec }}
  {{- toYaml .deploymentSpec | nindent 2 }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      {{- if .podSpec }}
      {{- toYaml .podSpec | nindent 6 }}
      {{- end }}
      containers:
        - name: {{ .name }}
          {{- if .resources }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          {{- end }}
          image: {{ .image }}
          {{- if .env }}
          env:
            {{- toYaml .env | nindent 12 }}
          {{- end }}
          {{- if .volumeMounts }}
          volumeMounts:
            {{- toYaml .volumeMounts | nindent 12 }}
          {{- end }}
          {{- if .containerSpec }}
          {{- toYaml .containerSpec | nindent 10 }}
          {{- end }}

        {{- if ( default false .anubis ) }}
        - name: anubis
          image: ghcr.io/techarohq/anubis:v1.24.0@sha256:4bdf6ddd1a8dc8bfe7a33d823a1cb72157885ca4fd3ee749654b21cba732e439
          env:
            - name: "TARGET"
              value: "http://localhost:{{ .service }}"
            - name: "DIFFICULTY"
              value: "4"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
        {{- end }}

      {{- if .volumes }}
      volumes:
        {{- toYaml .volumes | nindent 8 }}
      {{- end }}
      {{- if .imagePullSecret }}
      imagePullSecrets:
        - name: {{ .imagePullSecret }}
      {{- end }}
---

# svc generation
{{- if .service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  selector:
    app: {{ .name }}
  ports:
    - protocol: TCP
      name: {{ .service | quote }}
      port: {{ .service }}
      targetPort: {{ .service }}
    {{- if ( default false .anubis ) }}
    - protocol: TCP
      name: "anubis"
      port: 8923
      targetPort: 8923

    {{- end }}
{{- end }}

---
# pvc generation
{{- if .pvc }}
{{- range .pvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ . }}
spec:
{{- if $.Values.storageClass }}
  storageClassName: {{ $.Values.storageClass }}
{{end}}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
{{- end }}
{{- end }}

---
{{- if .ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
spec:
  ingressClassName: {{ $.Values.privateIngressClass}}
  rules:
  - host: {{ .ingress.domain }}
    http:
      paths:
      - backend:
          service:
            name: {{ .name }}
            port:
              number: {{ .service }}
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .ingress.domain }}
---
{{- if ( default false .ingress.public ) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}-tunnel

  # by default a kybervo policy will add the geoblock middleware to all ingresses
  # if the endpoint needs to be accessible worldwide, we set a specific label
  # that will opt-out the policy by kyverno
  {{- $geoblock := hasKey .ingress "geoblock" | ternary .ingress.geoblock true}}

  {{- if not $geoblock }}
  # so kyverno will not add the default geoblock
  labels:
    cocointhe.cloud/geoblock-disabled: ""
  {{- end }}


spec:
  ingressClassName:  {{$.Values.publicIngressClass}}
  rules:
  - host: {{ .ingress.domain }}
    http:
      paths:
      - backend:
          service:
            name: {{ .name }}
            port:
              number: {{ ternary "8923" .service (default false .anubis) }}
        path: /
        pathType: Prefix
{{- end }}
{{- end }}
{{- end }}

---



# configmap generation
{{- range $name, $data := .Values.configmaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
data:
  {{- range $key, $value := $data }}
  {{ $key }}: |
    {{- $value | nindent 4 }}
  {{- end }}

---
{{- end }}
