apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard
spec:
  interval: 1h
  chart:
    spec:
      chart: ./appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1h
  values:
    apps:
      - name: adguard
        image: adguard/adguardhome:v0.107.78@sha256:1ea34eafe5dc691007946e8eaab7bf46b0de9412f39213d8c06e48b53bf9a6c5
        deploymentSpec:
          strategy:
            type: RollingUpdate
            rollingUpdate:
              maxUnavailable: 0
              maxSurge: 1
        podSpec:
          hostNetwork: true # for the dhcp server
        containerSpec:
          livenessProbe:
            exec:
              command:
                - nslookup
                - cocointhe.cloud
                - 127.0.0.1
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 4
        volumes:
        - name: adguard-data
          persistentVolumeClaim:
            claimName: adguard-data
        volumeMounts:
        - mountPath: "/opt/adguardhome/conf"
          name: adguard-data
        - mountPath: "/opt/adguardhome/work"
          name: adguard-data
        pvc:
          - adguard-data
        service: 42080
        ingress:
          domain: adguard.cocointhe.cloud
--- # loadbalancer service for DNS queries
apiVersion: v1
kind: Service
metadata:
  labels:
    app: adguard-dns
  name: adguard-dns
spec:
  ports:
  - port: 53
    protocol: UDP
    targetPort: 53
  selector:
    app: adguard
  type: LoadBalancer
