apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secret
stringData:
  OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:MXPwLbcRiH92qktU7E5T+2O16cl2LQf7YdzhWLeeiS69cnzp,iv:O/2EApu1ZQJwthdoT8ieh+cSHQTl0ijlxSXdlCAXVpY=,tag:DdaSmnpg4GqlyHI3UjHOWQ==,type:str]
  OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:ZdOQjPvy5rzq95cTDiydb/PlE+/2KKodfgQIKYB+LN0=,iv:QrrI9gPEpdxRSCG4vh6je25kkOSNgxURltyqofpWNK0=,tag:O3U55vAW5EweeYJD7Aovww==,type:str]
  OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:qhijNlEycTl5shT7eWL3rsA/Qfo3vyRxPkV42jocz/U=,iv:39gR6HwGFcLBgydzJegnAXK5wpTix0i5WYCXqwaFCXY=,tag:5y6E62bbPQqr1/yrdaGz9g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvS2s5bFRWWHEwSEJqVG5G
        NFE3aXFOUzZUZ1hEM0VVeG41NEFGK21MS1NjCi94RERmbm5xUXduUk9rRElPMGZG
        cWZ2MHYwQXNSVWdvUHBMSFFQVGVwUHMKLS0tIDRSK3pWbVB1OXJkSzhZZjBVQWdX
        dWlJR2xmMlEvUXFIRjl2YWEyYi90TVkKfWk4lSZjSWoLb6kOZ4BeVI0sSiPoHdt+
        7brwoyy4Br7ywvqTEdyCrnB2EgBNHg/2GiEDrA99dJtGrM7o7O9AsQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16xc3m2q69s2le4hah3pcne50qn6mljhgc9mxekskwf0mp8fc0vaq5q5dz2
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$|secrets$)
  lastmodified: "2026-06-26T15:36:41Z"
  mac: ENC[AES256_GCM,data:ExJruuD1EVhKSP/5kSippKsiGPOGW0WyARGDi6n9RTzBCGe1NT4cS0F78L/5rbLbV6AG1LqaoIAZ6K5j06w+5Ubv2hTGJ8kwCqtORjzf9uSJmTgX/6ATHOVgI91xFtZEgnJvZ2X/t3WG4RFbS7wNLSOxK5DT2fZmuKiR0nIVdvo=,iv:jAexralsDl+dmH1w5eCs6Aryb6iv8Gvcll/acgXqaaI=,tag:m6Z4Zz6Yvi6z8dg6vuDWeg==,type:str]
  version: 3.13.1
