apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: filebrowser
spec:
  interval: 1h
  chart:
    spec:
      chart: ./appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: filebrowser
        image: ghcr.io/gtsteffaniak/filebrowser:1.5.8-stable@sha256:68455d4953bad8e984e1bc5d112ed1e9c918a0a04f104c13c9ece50790308894
        volumeMounts:
          - name: filebrowser-data
            mountPath: /data
          - name: filebrowser-config
            mountPath: /home/filebrowser/data/config.yaml
            subPath: config.yaml
        volumes:
          - name: filebrowser-data
            persistentVolumeClaim:
              claimName: filebrowser-data
          - name: filebrowser-config
            secret:
              secretName: filebrowser-config
        service: 8080
        ingress:
          domain: files.cocointhe.cloud
        pvc:
          - filebrowser-data
