apiVersion: v1
kind: Secret
metadata:
  name: garmin-config
stringData:
  values.yaml: ENC[AES256_GCM,data:8WO74HiXRECD1H6QxwAXC/LOre8Ge4ZTZfjLZAeGbEhMsdsL2vLLnDxj3qCtQdKUhGivkMCz9aCTuTyLREx0jxES3PCeSNrrVHKfCTswqAD7zU5a/AOsRyXL8AYV4Tf++J7Wbm31PfQjqxMrZ5iYSLj1uUjHM5aV5k5PyEU+9hN7BJ4LlpXJu0NVSa1l+zQu7ESI7XCniQLfxfBV8p0BaB7SO0Uyc4oYvYr/biS2moelQRuINWzNTfD6dlGrM8kSfj7kXXKz/smBUEkDb0sDVWIP6uwyT74TfIEr8MEM3rodCEv1B8P/X46q6a6EZJM7dDsq+3xF2owDZHIts9XV8SWs,iv:xj9Ym/Y1114gbpSSNQ4AknkfyZdBwtW1xvEayHoqFX8=,tag:yU9AuFmbhdUn1WRid23LiA==,type:str]
sops:
  age:
    - recipient: age16xc3m2q69s2le4hah3pcne50qn6mljhgc9mxekskwf0mp8fc0vaq5q5dz2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VGZwcTVqUEdxUGFyd3hz
        ZWsrV0daMEFCZTJGQ1d1Vk9oUUlaVjFKZ2xvCmhYYVUzaUpzWEt3RTA0ZjN4ZWtB
        dytjUFhVUllIR20ycnpVRGt6a1lwd0EKLS0tIC9HeFhWc01zZ2wwdU93cjYvT0t3
        dUMzWXh1T2I1MW90Mm5wYjRSdXI2dXMKIE26Ns0fxRdF0wnC2IAupc98viGwPi+Q
        mVlyRwMEdiq44cg9clALcvos8JRuYZPyj3KxR+u2Gz25UOepw0+Oeg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-03T20:10:36Z"
  mac: ENC[AES256_GCM,data:FQm5R1wRl8mHQduH6j9rLV1l9RludTHzl1L8/ZXxTFxSb8ICG7SPp8Yx9nloeXXJV832ie33DrkQokqBokG361MWSAArOPGMV61mi01eYxfqCN7d+jsgE5dPsMj7eeHl/bsjwbbBJVOYQl5dK358f9AP5frrt6sBISnB2erZ3LA=,iv:ietYUF0tKpP3Zlb++J20jwMMokdkquykh2J+1UYWUM4=,tag:Yk1nR28ARf0E5pjXqQgNaw==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$|secrets$)
  version: 3.12.1
