apiVersion: v1
data:
  token: ENC[AES256_GCM,data:YmigXr5mkStRC9ASsDL6WDymqbqkj8B3gYcMdFk3DKN9B8MUMS///donbDQ=,iv:ScMIPhqRPLex27Ve0dTqnXt2gZJRtz5NZ2cPueY/ZhM=,tag:XmdaEoKgoYKHGSJ7LCw5zw==,type:str]
kind: Secret
metadata:
  name: gitea-ci-token
type: Opaque
sops:
  age:
    - recipient: age16xc3m2q69s2le4hah3pcne50qn6mljhgc9mxekskwf0mp8fc0vaq5q5dz2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUU9JNjB4cTdFbXBQS0t1
        bGlMd3RnSVNGSThpU241WUdZME53WlRKWlVZCkpxTXpVZ2VJLzZJNzhaN04zbWZh
        STNER1RScXVwcmNLMHVLVkVZRFVmNVEKLS0tIFpyQ05NNWF5dUFndTVkYzZvYk54
        M1FRY1o2MjRXTHVTVlZ1azhoOHFkWHMK48xuZcF6SBhxgnrW05OMDBdN+toIMIzP
        nsfK5zE1mygjho0nUYAkIAMTBgfHuXSstIpL6FmKeVtzuHC6jiyXsQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T09:00:26Z"
  mac: ENC[AES256_GCM,data:qK2NPXvVrWiYe8hblJ8O3dRu+hgwO/Si2VB1J9+u5+4auQUS7H5s/K4kz8aLCOlfoiFTt0S3Ranw17/Qcaydsa0OfHCqExfKP0Y3jlIDfNK/niNCUFR+m/4dgcGdgEd7QGiiowWxs111J53MMurf8aKqEq1v+bMll9K88iy3zbU=,iv:uKqrma6Jmuttwn16UnfDCLEbXCbzv2kOlQ8WEPmIZvc=,tag:0GYhRbELcr3yK6VVMnoRYw==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$|secrets$)
  version: 3.12.2
---
apiVersion: v1
data:
  config.json: ENC[AES256_GCM,data:4toGSEh9j4rnk8JJf6PkENel3pMryaNLgRSVj3TFJinKuDfXc0fG1fGuMVbqDpAtCnblRDInZO1zoCA1cRadzLf92d4GsXbQenTWXYng53Vn2Y7hrk0Mq11OLaWoWDJT7dzkoFo=,iv:MY2s+6z3ITXCyMNAeiHibKsFyrmXrrEBupbZcbYvXlI=,tag:tzpxweyUgy7KgiVxXbQjBw==,type:str]
kind: Secret
metadata:
  name: runner-docker-config
sops:
  age:
    - recipient: age16xc3m2q69s2le4hah3pcne50qn6mljhgc9mxekskwf0mp8fc0vaq5q5dz2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUU9JNjB4cTdFbXBQS0t1
        bGlMd3RnSVNGSThpU241WUdZME53WlRKWlVZCkpxTXpVZ2VJLzZJNzhaN04zbWZh
        STNER1RScXVwcmNLMHVLVkVZRFVmNVEKLS0tIFpyQ05NNWF5dUFndTVkYzZvYk54
        M1FRY1o2MjRXTHVTVlZ1azhoOHFkWHMK48xuZcF6SBhxgnrW05OMDBdN+toIMIzP
        nsfK5zE1mygjho0nUYAkIAMTBgfHuXSstIpL6FmKeVtzuHC6jiyXsQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T09:00:26Z"
  mac: ENC[AES256_GCM,data:qK2NPXvVrWiYe8hblJ8O3dRu+hgwO/Si2VB1J9+u5+4auQUS7H5s/K4kz8aLCOlfoiFTt0S3Ranw17/Qcaydsa0OfHCqExfKP0Y3jlIDfNK/niNCUFR+m/4dgcGdgEd7QGiiowWxs111J53MMurf8aKqEq1v+bMll9K88iy3zbU=,iv:uKqrma6Jmuttwn16UnfDCLEbXCbzv2kOlQ8WEPmIZvc=,tag:0GYhRbELcr3yK6VVMnoRYw==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$|secrets$)
  version: 3.12.2
