apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 10m
  chart:
    spec:
      chart: ./appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: immich-server
        image: ghcr.io/immich-app/immich-server:v3.0.1@sha256:46dedfc5848f7313bd6b584ea9f2648057430307aad6de56de968f6710a72cae
        service: 2283
        containerSpec:
          envFrom:
            - secretRef:
                name: immich-config
        # podSpec:
        #   affinity:
        #     podAntiAffinity:
        #       requiredDuringSchedulingIgnoredDuringExecution:
        #       - labelSelector:
        #           matchExpressions:
        #           - key: app
        #             operator: In
        #             values:
        #             - immich-machine-learning
        #         topologyKey: "kubernetes.io/hostname"
        ingress:
          domain: immich.cocointhe.cloud
        volumeMounts:
          - name: server-data
            mountPath: /data
        volumes:
          - name: server-data
            persistentVolumeClaim:
              claimName: immich-server-data
        pvc:
          - immich-server-data

      - name: immich-machine-learning
        image: ghcr.io/immich-app/immich-machine-learning:v3.0.1@sha256:cb2128c5cbc554fdaa2a036fb4419c808a9f3e0f27170e569dd9e727243da909
        service: 3003
        env:
          - name: TRANSFORMERS_CACHE
            value: /cache
        # podSpec:
        #   affinity:
        #     podAntiAffinity:
        #       requiredDuringSchedulingIgnoredDuringExecution:
        #       - labelSelector:
        #           matchExpressions:
        #           - key: app
        #             operator: In
        #             values:
        #             - immich-server
        #         topologyKey: "kubernetes.io/hostname"
        containerSpec:
          envFrom:
            - secretRef:
                name: immich-config
        volumeMounts:
          - name: ml-cache
            mountPath: /cache
        volumes:
          - name: ml-cache
            persistentVolumeClaim:
              claimName: immich-ml-cache
        pvc:
          - immich-ml-cache

      - name: immich-valkey
        image: docker.io/valkey/valkey:9.1@sha256:e69af20ab48e499c263627ee18bf5f568f3064f054019c097ca14d52872be0bb
        service: 6379

      - name: immich-postgres
        image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
        deploymentSpec:
          strategy:
            type: Recreate
        service: 5432
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: immich-config
                key: DB_PASSWORD
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: immich-config
                key: DB_USERNAME
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: immich-config
                key: DB_DATABASE_NAME
          - name: POSTGRES_INITDB_ARGS
            value: "--data-checksums"

        volumeMounts:
          - name: pg-data
            mountPath: /var/lib/postgresql/data
        volumes:
          - name: pg-data
            persistentVolumeClaim:
              claimName: immich-pg-data
        pvc:
          - immich-pg-data
