apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kaneo
spec:
  interval: 1h
  chart:
    spec:
      chart: ./appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1h
  values:
    apps:
      - name: kaneo-postgres
        image: postgres:18-alpine@sha256:6c538e7206ea40ff740ef27883529390a690b6ead6ba96b44c67a9f7c638e8fd
        containerSpec:
          envFrom:
            - secretRef:
                name: kaneo-config # Secret containing .env variables
        service: 5432
        pvc:
        - kaneo-postgres-data
        volumeMounts:
          - name: kaneo-postgres-data
            mountPath: /var/lib/postgresql/data
        volumes:
          - name: kaneo-postgres-data
            persistentVolumeClaim:
              claimName: kaneo-postgres-data

      - name: kaneo
        image: ghcr.io/usekaneo/kaneo:2.24.0@sha256:1f1fc35e45da5dd4a991ce741e2492510068449db3e37b8e06a4de13a91bce2a
        containerSpec:
          envFrom:
            - secretRef:
                name: kaneo-config # Secret containing .env variables
        service: 5173
        ingress:
          domain: kaneo.cocointhe.cloud
