apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kaneo
spec:
  interval: 1h
  chart:
    spec:
      chart: ./appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1h
  values:
    apps:
      - name: kaneo-postgres
        image: postgres:16-alpine@sha256:cf78e76683b9ca8c5733cbbdce6c9262b45b6767934dd0a95e671f9a0fc20685
        containerSpec:
          envFrom:
            - secretRef:
                name: kaneo-config # Secret containing .env variables
        service: 5432
        pvc:
        - kaneo-postgres-data
        volumeMounts:
          - name: kaneo-postgres-data
            mountPath: /var/lib/postgresql/data
        volumes:
          - name: kaneo-postgres-data
            persistentVolumeClaim:
              claimName: kaneo-postgres-data

      - name: kaneo
        image: ghcr.io/usekaneo/kaneo:2.19.1@sha256:143ccc2dc6f8989c1ad7e9958234aaaec4f06610978f3cef5330db06cad19008
        containerSpec:
          envFrom:
            - secretRef:
                name: kaneo-config # Secret containing .env variables
        service: 5173
        ingress:
          domain: kaneo.cocointhe.cloud
