apiVersion: v1
stringData:
  AUTH_SECRET: ENC[AES256_GCM,data:w80OonpEfizNBhEBVkS2GvzThhrwg3rwuUyYF/eOqK8dWdCdAEB1XPXVqMi8MkX+vbHFE42qz+n0FiCJaqySsQ==,iv:YWBVaME4hwOaNa+fXTIbU+FqwlO6VxkXVPFw6xaYaBU=,tag:EAw7cEs3XXlFmtJTUN+SFA==,type:str]
  KANEO_CLIENT_URL: ENC[AES256_GCM,data:Ya/sSrhCcsaVr9mxhWj8OWSaX1025zKR6xTmwmE=,iv:3uE+HxcgB+YFLxgopdfin4AUcX1WpZOiDEoVQjfAgWc=,tag:UxSeG7QW+Sf+EB7E+FexjQ==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:J6QwE7k=,iv:ip2fh5K7Kf4hCdQbcbfhOOKvTGRixRnpybc6k9G1ozE=,tag:G8/cmXwqVaRMpvRswug9HQ==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:NZJ5VtFsBPn+n9EU93JJ4m421Zs/djhvabCujRJEtxDMMiEvuhLiP91dagNf6QVyyIrfXQ1GHLMcfxdWi+utBVvxYPs5wT8561d18kCSzuvG+GDjkd99jnOxl64c,iv:IcG8Pg8glmiO/jpmFL/lEhnBjqeqvJR3bonKM6iEfDM=,tag:hqeKFosn/VqoBFFfmNBZnA==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:8lXk6wb6+64eLwG2ED7CrhN9Xuf3/C3UIf3xF0ccJfvq3wwqqzVuoTOkjPf1Jvbm,iv:12KqW5xPUmpMXXAnotLgo7UF/tLBtBkcTs5KA+78/e0=,tag:Z9W0QIIA7Wf9VAkkb8UvVA==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:LQONiBc=,iv:k0Mf+0UUEbup8tydi6pIHnnbS4ur/HmPy0pOqOcQLTg=,tag:8sQeYmrS+N3QO1JTVBcz1w==,type:str]
  DISABLE_GUEST_ACCESS: ENC[AES256_GCM,data:cyB2Ug==,iv:aNopLdknlwJ5H8AUS4D0Nd09xeUpIpc7NJJAAzO7XIA=,tag:1aa1MweOhu1cJmbI+F4WKg==,type:str]
  CUSTOM_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:aL8mcAV1nWoeK+28XhpLvgvQoCauyxQrvV1hB33lSA/UOpJ6,iv:7k7BeK4vnLMSuJI5Yo10n3yDB4PdEm8rgJciqlqKWMI=,tag:jjUj6bzzAr9R2Rtx7YRm1A==,type:str]
  CUSTOM_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:2SX0+WsQXmqSqzru+OBtK9tOT4AbqrtMv5xYKCyJVyw=,iv:Hz/5WJDpiCMJpHIaNhJX+qMsXbIJvuOsZCIKW28gKvU=,tag:rzp6c1fBgpTcy8B3i9/tWQ==,type:str]
  CUSTOM_OAUTH_DISCOVERY_URL: ENC[AES256_GCM,data:XHD+GKPIoPvLQBX1aVNSDIWwpAGgqwSR/qLm0Oxb7AJC6eVRhCYnrsfJcQL+GDRUeTkiIQzX+C5Dgym2p+KUPiM=,iv:NZpDXpzXS9ZGvBGYHwzzF1rqYkKoZrjAExZ1/8KSe+8=,tag:zxqDaak9uy1AvSV01dDxnQ==,type:str]
  CUSTOM_OAUTH_SCOPES: ENC[AES256_GCM,data:kRt66d1QGzGxARcV4Xk9Gsyroig=,iv:WDWbp1lql+ek1C/7zwMibmfuSWTvQU7wctZZZp/KF4o=,tag:K2aBOlNIFcd+LIliDidocw==,type:str]
  CUSTOM_AUTH_PKCE: ENC[AES256_GCM,data:Pq8DLsU=,iv:T07HJL16WoSeyYTeXS+/tkAZ23g98eaRSzEA5663aKA=,tag:7fhZimPfKzO4ND/EwwEWTQ==,type:str]
  KANEO_ALLOW_PRIVATE_WEBHOOK_DESTINATIONS: ENC[AES256_GCM,data:2iXS/A==,iv:x4LQehtfILH9UwlBuAOIzbDW2m9WUOGpH8qCsTWJtzI=,tag:ur+7zxUbSXNRe6VwlakNnA==,type:str]
kind: Secret
metadata:
  name: kaneo-config
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMng2aVNMUFR6ZjVZWk9u
        SXJpYm9iY2htNUlyNkJtdnBmbGVzV2pDWkhZCmpQbm5vaUM3V2tnZHBQNUVuT2I2
        S2pHeWc3MkR6WmQxSUxqcjFuV08zMTQKLS0tIE1MTjBWVmQ4dkVHZHVEOURRczhj
        TkZKR2pCL0tiU3Nqc3FRL0t3emRpU0UKNEH+PXkNkTUYHgRsiaAjWQUe5JmButq6
        owppIhzhY7f/DrStDcL3DfWEXENxuX/Ay0/Rq1ohhmFMQKuv+EJ2AQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16xc3m2q69s2le4hah3pcne50qn6mljhgc9mxekskwf0mp8fc0vaq5q5dz2
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$|secrets$)
  lastmodified: "2026-08-19T19:55:58Z"
  mac: ENC[AES256_GCM,data:WAQqE5LyvVtyf9WJi2+Efkw+CKnuBHvjiw1IpQtwNP+DMsSy1XrWp4XzyLdhRjL6zJmleU94cx0PbqeW6r1BVj0nDFkGeZb1BGFc6KkRP6lWWKv1n+YimF2uASWl6ZiMPk5XUOXaPAksLtHzwymUWQWgEEGLuBiCdT78uFLMCH8=,iv:OFh0L5WQNY/FpzeKShdc6nrg85ta6QAER9PwabPakto=,tag:6gYEyLdqpOjPoV8c6rHzuw==,type:str]
  version: 3.13.3
