apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
spec:
  interval: 10m
  chart:
    spec:
      chart: ./appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: uptime-kuma
        image: louislam/uptime-kuma:2.5.4-slim@sha256:6054e0b9b7c3798b8ac066b58fd9bb37afe79bd6a3d8baf21ec6745e4ff0d17b
        service: 3001
        volumeMounts:
          - name: uptime-kuma-data
            mountPath: /app/data
        volumes:
          - name: uptime-kuma-data
            persistentVolumeClaim:
              claimName: uptime-kuma-data
        ingress:
          domain: uptime.cocointhe.cloud
        pvc:
          - uptime-kuma-data
---
# # kuma checks
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: allow-kuma-checks
# spec:
#   podSelector:
#     matchLabels:
#       app: uptime-kuma
#   policyTypes:
#   - Egress
#   egress:
#   # for dns/http checks
#   - to:
#     - ipBlock:
#         cidr: 0.0.0.0/0
#     ports:
#     - protocol: UDP
#       port: 53
#     - protocol: TCP
#       port: 443
#   # for local infra checks
#   - to:
#     - ipBlock:
#         cidr: 192.168.1.0/24

#     # for remote infra checks
#   - to:
#     - namespaceSelector:
#         matchLabels:
#           kubernetes.io/metadata.name: tailscale
