apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless
spec:
  interval: 10m
  timeout: 20m
  chart:
    spec:
      chart: ./appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: paperless-ngx
        image: ghcr.io/paperless-ngx/paperless-ngx:3.1.1@sha256:73a1d0bcc5b50cb501f084da795722aa5e2988c6bc9b26ca1ae493a57a490c06
        volumeMounts:
          - name: paperless-data
            mountPath: /usr/src/paperless/data
          - name: paperless-media
            mountPath: /usr/src/paperless/media
          - name: paperless-export
            mountPath: /usr/src/paperless/export
          - name: paperless-consume
            mountPath: /usr/src/paperless/consume
        env:
          - name: PAPERLESS_REDIS
            value: redis://paperless-redis:6379
          - name: PAPERLESS_OCR_LANGUAGE
            value: fra
          - name: PAPERLESS_BIND_ADDR
            value: 0.0.0.0
          - name: PAPERLESS_URL
            value: https://paperless.cocointhe.cloud
        containerSpec:
          envFrom:
            - secretRef:
                name: paperless-oidc-config
        volumes:
          - name: paperless-data
            persistentVolumeClaim:
              claimName: paperless-data
          - name: paperless-media
            persistentVolumeClaim:
              claimName: paperless-media
          - name: paperless-export
            persistentVolumeClaim:
              claimName: paperless-export
          - name: paperless-consume
            persistentVolumeClaim:
              claimName: paperless-consume

        service: 8000
        ingress:
          domain: paperless.cocointhe.cloud
        pvc:
          - paperless-data
          - paperless-media
          - paperless-export
          - paperless-consume

      - name: paperless-redis
        image: redis:8.4.0-bookworm@sha256:c22af04bb576503bf16b3e34a1fd2fd82de0f765afd866d2e380145e0af30d78
        service: 6379
