apiVersion: v1
kind: Secret
metadata:
  name: renovate-env
type: Opaque
stringData:
  RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:A0iZQmRqyM+ihTlDvyhjBpylCjmg12Cn3GGavBqjO/Q/ZQ==,iv:OBOk/XQedBej9V4wGYgRNci6yG3QHyTz5eYaPQlQdJY=,tag:pHqCobDN5K6VwbXw51bYxg==,type:str]
  RENOVATE_PLATFORM: ENC[AES256_GCM,data:Khqw3bE=,iv:8cxUr0/tlS5xL2bs4G9xF0TJ2oLRC65dSlQZ6RXtK60=,tag:/KcNKsewdV0iIrO1XUM55A==,type:str]
  RENOVATE_ENDPOINT: ENC[AES256_GCM,data:hJJ+KpE645j2lXjHM5gMUFIhLPiSfDpi6+DADqk=,iv:pjZaBB7gl+018husWIUfdIXnyRracUMUtzNv/6nkWAs=,tag:htw/WKXwpAti0Oq92GtWig==,type:str]
  RENOVATE_TOKEN: ENC[AES256_GCM,data:J0dhduRr4fZ9tCr10uext0x7m6rqw5nFdPAvRkt4yloOVxWfIjguug==,iv:v8tdK/MFzFVAjy5Qhund21rV6NT4dJXef64j+hqNwdk=,tag:xSr3ERE0KLcoHz0dMr+oqg==,type:str]
  RENOVATE_BASE_DIR: ENC[AES256_GCM,data:3HPu1wEr2hOviFxkRQ==,iv:MNquf5VLjJz7TYJWq6R9KtnVUJibvMrLJo5OBd2aevU=,tag:LhiFe60MEdMf+THUjnKTWA==,type:str]
  RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:dmw+dJ+C5fRL5Vcte2Mdz79+AmuSQ8V+trNo1CAQQbFTjFzHc8lw1w==,iv:G6/fdQXgx/xq158Q3L6S7lOTR/uaF19N+Tveme+M22A=,tag:EC5imFivA/GXM7vEJ2b7Wg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXU2IrZkZsZDRvTm8relpY
        ejVTeHNRZk5ZODk5cHN1M2hZMmVCZkhiSkJrCi8wNmVQeWk3NzFyUXlubTNZVkEr
        cUtkSTNBMHd4SVdKNTl5SldMdStjRncKLS0tIFVYeTc1UHRNVnAwWVlCMXdJUU1B
        Q2M1SVExcERUeG9BM0pGbXRhN0ViaUkKp19uWMKqVGzu1xfXobLoqXtXwWtLifIJ
        PDncIz+GaAb4X3QU3AwlA8jfnhhOJhXQqQGoDKcT5SIo+AhGEARVhA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16xc3m2q69s2le4hah3pcne50qn6mljhgc9mxekskwf0mp8fc0vaq5q5dz2
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  lastmodified: "2026-06-24T18:05:09Z"
  mac: ENC[AES256_GCM,data:r0PgEmBmvuWWI4smWeXWvAx1uNOaPl4Ri1J1q+nyMF1KwkG+WsRfE7CD9D9O24C6eTzatxpdfnbIjRYU6YGn0xiYtdP4ymrDUQlarWxs2QZHMGFLd9a5dvbnMnBaX57p+4uZ/YglrzMIVjPYPi3FmDzyddM0sHm82s2EVFpceNA=,iv:zWp4mK6szanBbK0i49DiBHkSkHVSIXFyH1U3AKQjqIQ=,tag:mXcfb0o90pA4rRSyndNUZw==,type:str]
  version: 3.13.1
