apiVersion: v1
kind: Secret
metadata:
  name: renovate-env
type: Opaque
stringData:
  RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:A0iZQmRqyM+ihTlDvyhjBpylCjmg12Cn3GGavBqjO/Q/ZQ==,iv:OBOk/XQedBej9V4wGYgRNci6yG3QHyTz5eYaPQlQdJY=,tag:pHqCobDN5K6VwbXw51bYxg==,type:str]
  RENOVATE_PLATFORM: ENC[AES256_GCM,data:vMfjsEqF,iv:U/8/OQBy1aR8heRtk0ABC3C9yvWPPOsCneGqueUqPTY=,tag:o8Jk31V3yPyXnkLueT1Ajw==,type:str]
  RENOVATE_TOKEN: ENC[AES256_GCM,data:fLNPltooEMAEQlhhIbPpqiezI5evVBi42NyW9P5qhAdTLo6nxFa03g/2toDxgFubKCSJG6csvs105u6aMqGig9I4h4C5lkV/rrFII21tco7qgs2jX3mlvru22dV1,iv:uoPgNLBTvjAAXygy34YFf+5juL5UD9OMzM2JAXp7qXs=,tag:xGa5IZTF9bRqBoc5rAID0g==,type:str]
  RENOVATE_BASE_DIR: ENC[AES256_GCM,data:3HPu1wEr2hOviFxkRQ==,iv:MNquf5VLjJz7TYJWq6R9KtnVUJibvMrLJo5OBd2aevU=,tag:LhiFe60MEdMf+THUjnKTWA==,type:str]
sops:
  age:
    - recipient: age16xc3m2q69s2le4hah3pcne50qn6mljhgc9mxekskwf0mp8fc0vaq5q5dz2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXU2IrZkZsZDRvTm8relpY
        ejVTeHNRZk5ZODk5cHN1M2hZMmVCZkhiSkJrCi8wNmVQeWk3NzFyUXlubTNZVkEr
        cUtkSTNBMHd4SVdKNTl5SldMdStjRncKLS0tIFVYeTc1UHRNVnAwWVlCMXdJUU1B
        Q2M1SVExcERUeG9BM0pGbXRhN0ViaUkKp19uWMKqVGzu1xfXobLoqXtXwWtLifIJ
        PDncIz+GaAb4X3QU3AwlA8jfnhhOJhXQqQGoDKcT5SIo+AhGEARVhA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-29T19:52:09Z"
  mac: ENC[AES256_GCM,data:MWkZR4mnQZbyewFP3r4mVPdJxQs5lGGpfHWykyvzNmqq253cU4pLh2lP4ivdTd2xm83Bfr7+pVmBYjrWNBe2BiedsVHokOwPBtYZwma7tfnd6ZucRQ26DRWFoffxOUbBUtOODUP50AOIhWVOmDjy/hZLj4as1YK+vN/IYHlj760=,iv:fcpF3rkpHLpqabts+tapGdzQZKlNVS6VuLEbWT6EgG8=,tag:BVhjMvPGUnPN14fL1PScLw==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.12.2
