apiVersion: v1
kind: Secret
metadata:
  name: renovate-env
type: Opaque
stringData:
  RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:A0iZQmRqyM+ihTlDvyhjBpylCjmg12Cn3GGavBqjO/Q/ZQ==,iv:OBOk/XQedBej9V4wGYgRNci6yG3QHyTz5eYaPQlQdJY=,tag:pHqCobDN5K6VwbXw51bYxg==,type:str]
  RENOVATE_PLATFORM: ENC[AES256_GCM,data:Pcj/V6ZdRA==,iv:ttq9HC3hl4DGVgYTlHNZkdaue9wc7Aqacga/1j5i7Hg=,tag:a5anBqUOeQIzGhsUA2lxfw==,type:str]
  RENOVATE_TOKEN: ENC[AES256_GCM,data:5EXvThWQ5YHKPryuJvbLpvnbOk2j5vAUcq0Xp4V+zP0g7XlXnEMJ7g==,iv:5HrhbpPGq0gQpe01c7TaP+ysPoXZfBQyM3OSNXwqQ5c=,tag:ZP5KHuT4N045/tilYbqgPA==,type:str]
  RENOVATE_BASE_DIR: ENC[AES256_GCM,data:3HPu1wEr2hOviFxkRQ==,iv:MNquf5VLjJz7TYJWq6R9KtnVUJibvMrLJo5OBd2aevU=,tag:LhiFe60MEdMf+THUjnKTWA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXU2IrZkZsZDRvTm8relpY
        ejVTeHNRZk5ZODk5cHN1M2hZMmVCZkhiSkJrCi8wNmVQeWk3NzFyUXlubTNZVkEr
        cUtkSTNBMHd4SVdKNTl5SldMdStjRncKLS0tIFVYeTc1UHRNVnAwWVlCMXdJUU1B
        Q2M1SVExcERUeG9BM0pGbXRhN0ViaUkKp19uWMKqVGzu1xfXobLoqXtXwWtLifIJ
        PDncIz+GaAb4X3QU3AwlA8jfnhhOJhXQqQGoDKcT5SIo+AhGEARVhA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16xc3m2q69s2le4hah3pcne50qn6mljhgc9mxekskwf0mp8fc0vaq5q5dz2
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  lastmodified: "2026-06-17T18:00:30Z"
  mac: ENC[AES256_GCM,data:vjEVUj8DlKSMCm++ZsrabZIe3CgqFXMdZumkNEBFgM3WWtmNWYPZRuDH2lk0L/gMDWT4uPyrg/xb5NSiM8TFKIvpS5C589uaYhS0aqeJVLBbIM+KHu+4hKeMiq4qcb0Qqh6ajP1cQh6MjOYGMMSWELuqBAQNVLUTODZBe/m4qqM=,iv:kbdeBFdADclswS1++Yi0QMGqXX54qObe9eMktD/tJ04=,tag:muy6A6G2DBTzq5KMFgeLYQ==,type:str]
  version: 3.13.1
