apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: "0 20 * * *"
  timeZone: "Europe/Paris"
  # suspend: true
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          # volumes:
          #   - name: renovate-cache
          #     persistentVolumeClaim:
          #       claimName: renovate-cache
          containers:
            - name: renovate
              image: renovate/renovate:44.30.4@sha256:e28fae22baff685b0c4d00277500b41886ff457bb6f89d7d08eaf82c95fae442
              args:
                - coco/cluster
              envFrom:
                - secretRef:
                    name: renovate-env
              # volumeMounts:
              # - mountPath: "/tmp/renovate"
              #   name: renovate-cache
          restartPolicy: Never

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: renovate-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
