apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: "0 20 * * *"
  timeZone: "Europe/Paris"
  # suspend: true
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          # volumes:
          #   - name: renovate-cache
          #     persistentVolumeClaim:
          #       claimName: renovate-cache
          containers:
            - name: renovate
              image: renovate/renovate:44.5.3@sha256:0de2072bc4c87e1744158adfb8ccd9f49c5bd2da5a0c14bc4b0c90a7cdaab54f
              args:
                - coco/cluster
              envFrom:
                - secretRef:
                    name: renovate-env
              # volumeMounts:
              # - mountPath: "/tmp/renovate"
              #   name: renovate-cache
          restartPolicy: Never

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: renovate-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
