apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: "0 20 * * *"
  timeZone: "Europe/Paris"
  # suspend: true
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: renovate-cache
            persistentVolumeClaim:
              claimName: renovate-cache
          containers:
            - name: renovate
              image: renovate/renovate:43.207.3@sha256:af0ea0750c46eda2f2af916d2a32228d699f1d69027f1396d4f8bbcb1497e818
              args:
                - k0rventen/tepore
              envFrom:
                - secretRef:
                    name: renovate-env
              volumeMounts:
              - mountPath: "/tmp/renovate"
                name: renovate-cache
          restartPolicy: Never

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: renovate-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi