apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sketchforge
spec:
  interval: 10m
  chart:
    spec:
      chart: ./appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: sketchforge
        image: ghcr.io/formsmith746/sketchforge-3d:main@sha256:7d3eac6d30e5c63e898bbe5bba750eb17b5ad224f7667c428dea035a501a3b37
        env:
          - name: SKETCHFORGE_SHARED_PROJECTS_DIR
            value: "/data/projects"
        volumeMounts:
          - name: sketchforge-data
            mountPath: /data/projects
        volumes:
          - name: sketchforge-data
            persistentVolumeClaim:
              claimName: sketchforge-data
        service: 3000
        ingress:
          domain: 3d.cocointhe.cloud
        pvc:
          - sketchforge-data
