# loosely based on https://warpgate.null.page/getting-started-on-helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: warpgate
spec:
  interval: 1h
  chart:
    spec:
      chart: ./appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1h
  values:
    apps:
      - name: warpgate
        image: ghcr.io/warp-tech/warpgate:0.29.1@sha256:a47b502039348c9f35b9fca222be1630cf975caf985d6e05ecdd186fbd1194d4
        containerSpec:
          # on first launch, shell in the container and do `warpgate setup`
          # command:
          #   - sleep
          #   - inf
          envFrom:
          - secretRef:
              name: warpgate-env
        volumeMounts:
          - name: warpgate-data
            mountPath: /data
        volumes:
          - name: warpgate-data
            persistentVolumeClaim:
              claimName: warpgate-data
        pvc:
          - warpgate-data

# due to warpgate exposing only an https port, we need
# to explicity configure the svc to redirect to https and
# ignore the certificate, otherwise traefik will return a 500
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: warpgate
spec:
  insecureSkipVerify: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: warpgate
spec:
  ingressClassName: traefik
  rules:
  - host: warp.cocointhe.cloud
    http:
      paths:
      - backend:
          service:
            name: warpgate
            port:
              number: 8888
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - warp.cocointhe.cloud

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
    traefik.ingress.kubernetes.io/service.serverstransport: warpgate-warpgate@kubernetescrd
  name: warpgate
spec:
  ports:
  - name: http
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: warpgate
  type: ClusterIP

---
# additional LoadBalancers for specific protocols (ssh/kubernetes)
apiVersion: v1
kind: Service
metadata:
  name: warpgate-protocols
spec:
  ports:
  - port: 2202
    protocol: TCP
    targetPort: 2202
    name: ssh
  - port: 8443
    protocol: TCP
    targetPort: 8443
    name: kubernetes
  selector:
    app: warpgate
  type: LoadBalancer
