apiVersion: v1
kind: Secret
metadata:
  name: warpgate-env
stringData:
  WARPGATE_ENCRYPTION_KEY: ENC[AES256_GCM,data:4nmbzyvt4mXWYLbJ/vOHPloQYnVSICqzQPSihE0GFpzoLpgFXOqDI6HZDvY=,iv:pzPBkFU327KiEDRo9VHP0RpzbCI8g1sKymwZ96ighD0=,tag:NezNiIMZRBcKodFAPeQiKw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1enhoVU0xVXdmVWNiV3cv
        V2d6eXg3Wi9WUmh4WWdnZGgvMDFJTmlLVFJrCkVqUU4zczlRMGlydkNkMHNtemJE
        NEJoZmkxNENJZjV5TUtYTjg1bS9rdDgKLS0tIDhFRGNGWkU5TE1ib0tweitvTEFW
        L1plT3dVYlh1L3I2UXpuVEthcTk2b0EKljbouaO37b99JN2Vzm3v/uFZE3jNfVBy
        O6gcHiIlg2MGm8eBNf9yv02P21dTPmzXslQu27m6FAQ+nAm6zNWQNQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16xc3m2q69s2le4hah3pcne50qn6mljhgc9mxekskwf0mp8fc0vaq5q5dz2
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$|secrets$)
  lastmodified: "2026-09-22T20:02:28Z"
  mac: ENC[AES256_GCM,data:ofxdN4CI/u533Z6QmCkJqOPwaVvncT59MbJlemon7h6hWQhTJAM2MgrtWo0yH0fBmTv47Xipeht91XxpwbOLz8prcx0nd17Q2Y0qpT8XfNJXkiFdIh8l/uD62IOQXT992U5i1BjF4mp4S3n+ss33xe2CYdq2qP4B04af7aUd42g=,iv:gjsUR6QJrFU3I0jlJ4q5bu5N8QCPbwl5MGBcAdMZ1O8=,tag:SEArswfOL3+xRLT8H9AdHA==,type:str]
  version: 3.13.3
