name: flux-local diff
on:
  pull_request:

jobs:
  diff:
    name: flux diff
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0

      - name: Run flux-local ks diff
        run: |
          flux-local diff ks --branch-orig main -A --path k8s/flux/ --output-file ks.diff
          flux-local diff hr --branch-orig main -A --path k8s/flux/ --output-file hr.diff

      - name: diff
        id: diff
        run: |
          # merge the 2 diff files
          cat hr.diff >> ks.diff

          # Message formatting based on diff

          {
            echo "diff<<EOF"
            if [[ -s "ks.diff" ]]; then
            echo "Here is the diff to main:"
            echo "\`\`\`diff"
            cat ks.diff
            echo "\`\`\`"
            else
              echo "No diff to main detected."
            fi
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Post comment
        env:
          BODY: ${{ steps.diff.outputs.diff }}
        run: |
          set -xeuo pipefail
          COMMENT_ID=$(curl -fsSL \
            -X POST -v \
            -H "Authorization: token ${{ secrets.GITEA_TOKEN }}" \
            -H "Content-Type: application/json" \
            ${{ github.server_url }}/api/v1/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
            --data-raw "$(jq -cn --arg body "$BODY" '{body: $body}')" \
            | jq -r '.id')

          echo "Posted comment ID: ${COMMENT_ID}"
