name: flux-local diff
permissions:
  contents: read
on:
  push:
    branches-ignore: ["main"]

jobs:
  diff:
    name: flux diff
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout main
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          ref: "${{ github.event.repository.default_branch }}"
          path: main
          token: ${{ secrets.GIT_TOKEN }}
      - name: Checkout PR
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          path: pr
          token: ${{ secrets.GIT_TOKEN }}

      - name: Run flux-local ks diff
        uses: docker://ghcr.io/allenporter/flux-local:v8.2.0@sha256:9c77739d8d7c71b808311693ea52d603d1ddb5190d3d4f23e47f6f33d5254602
        with:
          args: >-
            diff ks
            --path /github/workspace/pr/k8s/flux
            --path-orig /github/workspace/main/k8s/flux
            --all-namespaces
            --output-file ks.diff
      - name: Run flux-local hr diff
        uses: docker://ghcr.io/allenporter/flux-local:v8.2.0@sha256:9c77739d8d7c71b808311693ea52d603d1ddb5190d3d4f23e47f6f33d5254602
        with:
          args: >-
            diff hr
            --path /github/workspace/pr/k8s/flux
            --path-orig /github/workspace/main/k8s/flux
            --all-namespaces
            --output-file hr.diff
      - name: diff
        id: diff
        run: |
          # merge the 2 diff files
          cat hr.diff >> ks.diff

          # Message formatting based on diff

          {
            echo "diff<<EOF"
            if [[ -s "ks.diff" ]]; then
            echo "Here is the diff to main:"
            echo "\`\`\`diff"
            cat ks.diff
            echo "\`\`\`"
            else
              echo "No diff to main detected."
            fi
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Add Comment
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc
        with:
          message: |
            ${{ steps.diff.outputs.diff }}