name: flux-local test
permissions:
  contents: read
on:
  push:
    branches-ignore: ["main"]

jobs:
  test:
    name: flux test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - name: Run flux-local test
        uses: docker://ghcr.io/allenporter/flux-local:v8.3.0@sha256:dca65e5bcd71cb904216774ebfbc5d1f30a36d0b304293b851dfed2385c01b0c
        with:
          args: test --enable-helm --all-namespaces --path k8s/flux -v