apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bbox-exporter
spec:
  interval: 10m
  chart:
    spec:
      chart: ./appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: bbox-exporter
        image: gitea.cocointhe.cloud/coco/bbox:v0.1.0@sha256:b9bca9fbe7f387b21e505272be92cb1bd26cd0ee0774df97a0066bd6e008c239
        service: 8000
