apiVersion: v1
stringData:
    email: ENC[AES256_GCM,data:osNjgGbCPxbJ3FLMlYzNQi9n/Q==,iv:GvifZYWyPPjquCy4sZBjS1HypLYe6JyPQJ1bqtGzzPc=,tag:JCBQ097OvVxaAwKrjVXuaQ==,type:str]
    password: ENC[AES256_GCM,data:HQ1vzH2T/c68SVby183AucwqlF8pj7i7l5aA,iv:uGpj9Pk7bP7HoXfcUbB4Ubk5tSI57vTqyZyoqhmnevg=,tag:7JDARc+fXG49YJ+xq0lolg==,type:str]
kind: Secret
metadata:
    name: beem-exporter-secret
    namespace: watchtower
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16xc3m2q69s2le4hah3pcne50qn6mljhgc9mxekskwf0mp8fc0vaq5q5dz2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQlVtS3JjZFdYUU9ySmZI
            SDVKZ0ZYWXJyOE10MzZrR3FHMmRxVHRtVkY4CjY2YjhMNFdFYStGb2QwVng1T3A0
            M0p3TFpJRm1RK1VtNFlvL1hQSFZxWU0KLS0tIHJLWXQyQjBmZkFUSzlMMTE5RkR2
            cUxydFZ2Q1V5Q2FiZGd6MnA4dHJiR00Kh2Ojo3EHwgxz8dkb1DgCkNB8QB1nhRZD
            5jLJgRL61hq7WIas7hpQzr/1vFfMCJS4PAbp9jBstPMmLpiJ4YDyeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-23T20:28:15Z"
    mac: ENC[AES256_GCM,data:XTJrf6TyME0h0oDLoFXZS4cpcDMlou5qE/RnQk0ZShyxyehI9S7vHU1hmtXisdUKF6pPLX9rfPmX3Yltwcm5hXyVbtQ2OQuKt8QW86R0/umjNtrgXeKX+jmedkbGkpkbepaK5MNx1vHjEcaevqRtZ6pOr/U43GY7HXz0dImdMio=,iv:yMz6paSkXDWlybyon43CnYxRm2RnwZg1cCN+/+hnGVA=,tag:UTYM0puMlLozujkPiD7wKg==,type:str]
    pgp: []
    encrypted_regex: (token|email|^data$|^stringData$)
    version: 3.9.4