apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 10m
  chart:
    spec:
      chart: ./appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1h
  values:
    apps:
      - name: loki
        image: grafana/loki:3.7.7@sha256:d70e4659623f3e109af669cae76fe2a5dd5be54e2298fe8aed380d982fbc2500
        containerSpec:
          args:
            - -config.file=/etc/loki/local-config.yaml
            - -querier.parallelise-shardable-queries=false
            - -reporting.enabled=false
        volumeMounts:
          - name: loki-data
            mountPath: /loki
        volumes:
          - name: loki-data
            persistentVolumeClaim:
              claimName: loki-data
        service: 3100
        pvc:
          - loki-data
