apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 10m
  chart:
    spec:
      chart: ./appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1h
  values:
    apps:
      - name: loki
        image: grafana/loki:3.7.3@sha256:70b9f699fc9bb868b62f1cfd4f787dfa50242f1fd92e6089787d5d7daea75fe8
        containerSpec:
          args:
            - -config.file=/etc/loki/local-config.yaml
            - -querier.parallelise-shardable-queries=false
            - -reporting.enabled=false
        volumeMounts:
          - name: loki-data
            mountPath: /loki
        volumes:
          - name: loki-data
            persistentVolumeClaim:
              claimName: loki-data
        service: 3100
        pvc:
          - loki-data
