apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pool-counter
spec:
  interval: 10m
  chart:
    spec:
      chart: ./appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: pool-counter
        image: gitea.cocointhe.cloud/coco/pool-count:v0.2.0
        service: 8000
