apiVersion: v1
kind: Secret
metadata:
  name: prom-config
stringData:
  values.yaml: ENC[AES256_GCM,data:JpG78sJvvz+ent4bkgKmENgz9P9kQplhQywXeGUgCOv65wLiF8s52q3FvlWGJWHc/CLbTbEqyFDsOiBgw0EggNxg6Ziadwbch76MgQjTRNBlaKENhiFG2QsxNzkKMMHf94RuLK6h41fQKJUMkI3wYvkBRMUMfMZHoWSlJ7Evc3VnCK973nofQ6KhcUgsl0p38E+deZa90DJDVql36Y4zaQ5BqvbcwJE9Oy5QjQriY0gWWrXTA2UsGeQWDRdNEm5TPmfen6A0buAFdQTksOLS/Suuelm9I0ZY9YuzNkItp3OPwxCcgHpYDA2TboAuFwgkRY8rFhkDb3cEkc9kOvv5NkYmQpwjf/abzUntD/9GBWh+0Ql4aHA2W7wzYy11GLHjNNdBjyO5yTLRAjSZ0+30SNNhbLDjEWHblJg63a0McGj4sEtOExxZB055Yd6rCHhQaZvsfcAlP9FALq4RpKIRujrfwC1rRj4KgbOSpQBEF/4HdOvvMDbZDSMnvajBYf354RWNuXt9IbECSwyrDpOaWmvtxrhUSMq2sQ2F2WE7jf2i0IIJQDgHJySA5LPEg57/oT+9oE/gTBgeTgNYRYkQjlj7Em+ccWtGa0BA226GeixCibA3oN2i2i3OcH9ISZljWmWwAiSoM/JthvsC8aoT8tb2/M/dkN4poJcSai7epUK2SyfhHTxupgqHUqsWnjsb4/nXuFbdijqEj/oPei32NiE+WGHMw+YqVvcXco9SV54iAMpsX1cDerpiLMijIJ32QCEKyHeDjs7hL49nFcDMXrwEvWdIAezS7+mYIyM34c/KtXMsj9QZyZ4D3xLQId2PbgrniOeYeTqffd6WqjmR/2EZrpoEcdc/iHogMjJecerYiPZqegveqXOxpNWV00hPKlUjQRLI+s3X/sNVaSjz4GK3WUZo3wzyxYKvuIg/xfY5WmnYkVoBV8N+Eyqxd0bRK4vocxLGKmLDSNWiydgLe0GS2+hdD5TNy/2vdh/ah+QqRoG/s+C2RXhuts657SRXWO8oRp+Xwa3AQ/GXeBfn8mQGFuy2GtiNfV/mudp1WXFieqT30BTk0F5HZLgu/GxFAQHYsZJP4QlGj27u3QxsqYqK,iv:X5Hjmz6TH7dlNl6MikNCkHI30oEqA9WsYMVck3B4N+0=,tag:JzdJQugWKnDNeypwrIgpjw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNnBPNTZleTZGLzdOd29F
        VWdUeFBPRFdpYzFWSjBGU3pMV3VpQ2FKUG5JCklrbmxEYnFSdVNBZ3hFS2dGNUxC
        T1AzemxGSU5jMTl1bWx1bkpvZ0VRZEUKLS0tIER3UjlqTnlWNWc1K012aldUVEVI
        UE1KT1BEc0c5L2tNQVBlRVBsVlBDTjQKh33j1yOzEmpI24EKDHgJOoFIyKXgLC6u
        eIBxuRjfNLexjQ90M/QoRSwIKr1lQ2ZB01/oiYdgta5WR1IB4FkU+A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16xc3m2q69s2le4hah3pcne50qn6mljhgc9mxekskwf0mp8fc0vaq5q5dz2
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$|secrets$)
  lastmodified: "2026-07-11T11:37:46Z"
  mac: ENC[AES256_GCM,data:Z3oweHaw4PNguFJpgB6J7WzifOusjQ/89/ODd5DQwq4SH2GT+OC6PUdfieNF9nj0fhX298a8JA3U4YdWLB1GatoNh7BGFchm+3qDXAtWX7GWIjxi+GzlIMeaX/2+iRkxy50Yt+oVa7wOIyieMsKdp0/qH+Ahf3b7VkZq1HSpMFA=,iv:Xae0KM5NUsZH6m7jOVNShYYnNL4zhWKLJFrBoWrBaLo=,tag:8Eqizecxoapw24ecuU69mw==,type:str]
  version: 3.13.2
