apiVersion: v1
kind: Secret
metadata:
  name: prom-config
stringData:
  values.yaml: ENC[AES256_GCM,data:4Lga1MYo1ADH1OUbu6TI5LjmT5iEivYVDbeoVKa9OaebnplzvKStCaWvxt1Sw4eLkv41caALBcdkIHGFqqa3vsxLuRooWQ+Un6yQYT719z/ulHnmRh1BeNxGkl8tp7WTtk4avWyZgrICPhASu+1PsvPJkkUukP6DFeCRfe5BLbKT5H+B/QczvmjQAh5+qkwFrt0CAVYUfgg+laoINlpMJYuqrv5RgToMbnYdSdL1UDfqIdrbvHud2nbD9ldyf5hIbif++Q+8LLGJgONqKtIJOBcaWeJ1cHb2+AtRFIOvbYYZ2C8W64Lg10pAYlI2MyzO1bPkT/t8fhC8lAw6D8OFgXZjbvy3tk81BJh98DgAM8KOAT/sVKse3Ny7Qe4ZJVlerCwsTtoV70zLBuGYeqBczVHxfEd5c1KjyHsqmraPEYEdhEvrCkFoiDwTyK781Q78wFrXz5taAW3mKjDaHTfsodbqTSGlTl+IaKa5iSmM18MKm5XsCBa2hSXqe8hdywjSpfdsUtVbO5gwV3h/6OULVksFbPsPhXFDXU9m5NRdrBJX2hdt/mFUc4IS4aEWySVTIKDXsbxpprIIAmBLPiSKBblYZzmI7BcaOGsUTkBCV5oaZve/dUnPYGYuif8R1EaNQB5IM4VSYXHAYmKcRW/fA9llNh2hmrTsb2hFlES4w7bTM1eNhOWRMYCaSOJhVHZmjJGHRWpy/P5IeHDXZLC1fKDM91oLpyXuVQNIyFyef5BGSN7E8ttJkSlfjiNSbcjxs5Wi+aDBbPlwB9d9qGbfRnevDNqBvOYzoMzu8F+rlVPd22OhLCou0E9Zrtq5KluqpaB/nLNRBWhQiOZYxfMOrccp4e0G0Dn1YDkZ044czpQbG2wPJMykV4IUmmlbYHbGo6XnuDGICBdGFujgK+tmld9RnMrRflklaOGL7Q4r4C02iV50fRu1x3KzTvljP2Rm9bPfWNeynSf7ndK3EEY5Zfy1lq+g+2TAEvccfyP3jCHhqDlvwr6yTgqYmZETlHLa7wmtY4SczcOUCNV2P6LqmPj4xOMVWPDt7IagM8aqeaWPepjYaeTDjknu2b4AgJP8qgXuKiasRnslVCdvI2CA2nHTAsrwzeYdh+Eu/jf0i/oJWxk882rL98j+Ut1p5Q==,iv:gwEz3SUUN3wCznNB/4vOUvT/hL9JVxAoDIMIZJ2oT78=,tag:rcefvwTcbdsk6eTglBQZ5w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNnBPNTZleTZGLzdOd29F
        VWdUeFBPRFdpYzFWSjBGU3pMV3VpQ2FKUG5JCklrbmxEYnFSdVNBZ3hFS2dGNUxC
        T1AzemxGSU5jMTl1bWx1bkpvZ0VRZEUKLS0tIER3UjlqTnlWNWc1K012aldUVEVI
        UE1KT1BEc0c5L2tNQVBlRVBsVlBDTjQKh33j1yOzEmpI24EKDHgJOoFIyKXgLC6u
        eIBxuRjfNLexjQ90M/QoRSwIKr1lQ2ZB01/oiYdgta5WR1IB4FkU+A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16xc3m2q69s2le4hah3pcne50qn6mljhgc9mxekskwf0mp8fc0vaq5q5dz2
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$|secrets$)
  lastmodified: "2026-09-04T20:39:53Z"
  mac: ENC[AES256_GCM,data:63U91HmBSDbxN2EC9PIKYd3OU7lynIITNIqxeY49B+c5/HxzsjOXnhTcZPAiBpovbKlm03c4kmVbu0ASObEX5pxJUtdsP6ul2SUFcWGZ2q+nBTdH5Yej9U/xaq4J8VPJvNmhirXkockr4E8jskXlTE9gNhuzL/o1f7+WmLeUfCQ=,iv:OnzoCjuXjc5Q3vs/C99A7C/6+jxAWX557vnky3pU4Dc=,tag:nhJaBTYMQn/Dmtj0t7394A==,type:str]
  version: 3.13.3
